[package]
name = "bitcask"
version = "0.1.0"
edition = "2024"

[features]
bincode = ["dep:bincode"]

[dependencies]
crc = "3.0"
bincode = { version = "1.3", optional = true }
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.22.0"
log = "0.4.28"
env_logger = "0.11.8"
